🔧 fix: remove JSR-prohibited global augmentation[1]
[1]: because of this:

Run deno publish --dry-run --allow-dirty
Check file:///home/runner/work/internationalization/internationalization/mod.ts
Checking for slow types in the public API...
error[unsupported-global-module]: found global augmentations, which are not supported
Error:   --> /home/runner/work/internationalization/internationalization/CurrentLocale.ts:3:1
   |
 3 | declare global
   | ^^^^^^^^^^^^^^
   |
 4 | {
   | ^
   |
 5 |   interface Document
   | ^^^^^^^^^^^^^^^^^^^^
   |
 6 |   {
   | ^^^
   |
 7 |     documentElement: {
   | ^^^^^^^^^^^^^^^^^^^^^^
   |
 8 |       lang: string;
   | ^^^^^^^^^^^^^^^^^^^
   |
 9 |     };
   | ^^^^^^
   |
10 |   }
   | ^^^
   |
11 | }
   | ^
   = hint: remove the 'global' augmentation

  info: global augmentations are not supported because they can modify global types, which can affect other modules type checking
  docs: https://jsr.io/go/slow-type-unsupported-global-module

This package contains errors for slow types. Fixing these errors will:

  1. Significantly improve your package users' type checking performance.
  2. Improve the automatic documentation generation.
  3. Enable automatic .d.ts generation for Node.js.

Don't want to bother? You can choose to skip this step by
providing the --allow-slow-types flag.

error: Found 1 problem
Error: Process completed with exit code 1.